config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :playlists
  root to: 'playlists#index'
  get '/music', to: 'playlists#music'
  get '/jeux', to: 'playlists#jeux'
  get '/film', to: 'playlists#film'
  get '/new', to: 'playlists#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  enum category: [:musique, :film, :jeux]
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.all
  end
  def film
    @playlists = Playlist.all
  end
  def music
    @playlists = Playlist.all
  end
  def jeux
    @playlists = Playlist.all
  end

  # GET /playlists/1 or /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:title, :link, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html
  <head>
    <title>Play n Watch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Sawarabi+Gothic&display=swap" rel="stylesheet">
    <style>
      .tout{
        font-family: 'Sawarabi Gothic', sans-serif;
        background-color:#FFA1A1;
      }
    </style>
  </head>

  <body class="tout">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(250, 237, 237, 0.9)">
      <div class="container-fluid">
        <a style="margin-left=50px" class="navbar-brand" href="/">Play n Watch</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a style="font-size:15px" class="nav-link active" aria-current="page" href="/music">Musique</a>
            </li>
            <li class="nav-item">
              <a style="font-size:15px" class="nav-link active" aria-current="page" href="/film">Film</a>
            </li>
            <li class="nav-item">
              <a style="font-size:15px" class="nav-link active" aria-current="page" href="/jeux">Jeux</a>
            </li>
            <li class="nav-item">
              <a style="font-size:15px" class="nav-link active" aria-current="page" href="/new">Partage ta playlist !</a>
            </li>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to('Se deconnecter',destroy_user_session_path, method: :delete) %>
            </li>
            <% else %>
              <li class="nav-item">
                <a style="font-size:15px" class="nav-link active" aria-current="page" href="<%=new_user_session_path%>">se connecter</a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <div style="margin:50px">

      <%= yield %>
    </div>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist) do |form| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :lien %>
    <%= form.text_area :link %>
  </div>

  <div class="field">
    <%= form.label :catégorie %>
    <%= form.select(:category , ['musique', 'jeux', 'film']) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/film.html.erb
<p id="notice"><%= notice %></p>

  <thead>
  </thead>

  <tbody>
    <div class="row" style="margin-top:2em;padding:2em;background-color: rgba(250, 237, 237, 0.9);border-radius:30px 30px 30px 30px;height:auto;">
      <h1 style="margin: 50px;">Film</h1>
    <% @playlists.where(category:"film").each do |playlist| %>
      <div class="col-sm-3">
        <div id="bordure" class="card" style="width: 18rem; border-color:blue;background-color:#b8bae6">
          <div class="card-body">
            <h5 class="card-title"><%= playlist.title %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"style="color:blue;background-color:#b8bae6"><%= playlist.category %></li>
            <li class="list-group-item"style="background-color:#b8bae6"><a href=<%= playlist.link %> class="card-link">Lien</a></li>
            <li class="list-group-item"style="background-color:#b8bae6"><%= link_to 'Supprimer', playlist, method: :delete, data: { confirm: 'Êtes-vous sûr(e)?' } %></li>
          </ul>
        </div>
      </div>
    <% end %>
    </div>
  </tbody>

<br>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>


<style>

.vertical-center {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 200px;
  background-color: rgba(250, 237, 237, 0.9);
  border-radius:30px 30px 30px 30px;
}
</style>
  <div class="vertical-center">
    <p style="font-weight: bold;text-align:center; font-size:20px; ">Bienvenue sur Play n Watch. Ici, tu peux partager tes meilleures playlist Youtube, et consulter toutes celles de la communauté !</p>
  </div>
  <thead>
  </thead>

  <tbody >
    <div class="row" style="margin-top:2em;padding:2em;background-color: rgba(250, 237, 237, 0.9);border-radius:30px 30px 30px 30px;height:auto;">
      <h1 style="margin: 50px;">Les dernières playlists</h1>
  <% @playlists.order("created_at DESC").each do |playlist|
      case playlist.category
      when "musique"%>
        <div class="col-sm-3">
          <div id="bordure" class="card" style="width: 18rem; border-color:red;background-color:#ffd1d1">
            <div class="card-body">
              <h5 class="card-title" style="text-align:center"><%= playlist.title %></h5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"style="color:red;background-color:#ffd1d1"><%= playlist.category %></li>
              <li class="list-group-item"style="background-color:#ffd1d1"><a href=<%= playlist.link %> class="card-link">Lien</a></li>
              <li class="list-group-item"style="background-color:#ffd1d1"><%= link_to 'Supprimer', playlist, method: :delete, data: { confirm: 'Êtes-vous sûr(e)?' } %></li>
            </ul>
          </div>
        </div><%

      when "jeux"%>
        <div class="col-sm-3">
          <div id="bordure" class="card" style="width: 18rem; border-color:green;background-color:#b8e6b8">
            <div class="card-body">
              <h5 class="card-title"style="text-align:center"><%= playlist.title %></h5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"style="color:green;background-color:#b8e6b8"><%= playlist.category %></li>
              <li class="list-group-item"style="background-color:#b8e6b8"><a href=<%= playlist.link %> class="card-link">Lien</a></li>
              <li class="list-group-item"style="background-color:#b8e6b8"><%= link_to 'Supprimer', playlist, method: :delete, data: { confirm: 'Êtes-vous sûr(e)?' } %></li>
            </ul>
          </div>
        </div><%

      when "film"%>
        <div class="col-sm-3" >
          <div id="bordure" class="card" style="width: 18rem; border-color:blue;background-color:#b8bae6">
            <div class="card-body">
              <h5 class="card-title"style="text-align:center"><%= playlist.title %></h5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"style="color:blue;background-color:#b8bae6"><%= playlist.category %></li>
              <li class="list-group-item"style="background-color:#b8bae6"><a href=<%= playlist.link %> class="card-link">Lien</a></li>
              <li class="list-group-item"style="background-color:#b8bae6"><%= link_to 'Supprimer', playlist, method: :delete, data: { confirm: 'Êtes-vous sûr(e)?' } %></li>
            </ul>
          </div>
        </div><%
      end
    end %>
    </div>
  </tbody>

<br>

app/views/playlists/jeux.html.erb
<p id="notice"><%= notice %></p>

  <thead>
  </thead>

  <tbody>
    <div class="row" style="margin-top:2em;padding:2em;background-color: rgba(250, 237, 237, 0.9);border-radius:30px 30px 30px 30px;height:auto;">
      <h1 style="margin: 50px;">Jeux</h1>
    <% @playlists.where(category:"jeux").each do |playlist| %>
      <div class="col-sm-3">
        <div id="bordure" class="card" style="width: 18rem; border-color:green;background-color:#b8e6b8">
          <div class="card-body">
            <h5 class="card-title"><%= playlist.title %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"style="color:green;background-color:#b8e6b8"><%= playlist.category %></li>
            <li class="list-group-item"style="background-color:#b8e6b8"><a href=<%= playlist.link %> class="card-link">Lien</a></li>
            <li class="list-group-item"style="background-color:#b8e6b8"><%= link_to 'Supprimer', playlist, method: :delete, data: { confirm: 'Êtes-vous sûr(e)?' } %></li>
          </ul>
        </div>
      </div>
    <% end %>
    </div>
  </tbody>

<br>

app/views/playlists/music.html.erb
<p id="notice"><%= notice %></p>

  <thead>
  </thead>

  <tbody>
    <div class="row" style="margin-top:2em;padding:2em;background-color: rgba(250, 237, 237, 0.9);border-radius:30px 30px 30px 30px;height:auto;">
      <h1 style="margin: 50px;">Musique</h1>
    <% @playlists.where(category:"musique").each do |playlist| %>
      <div class="col-sm-3">
        <div id="bordure" class="card" style="width: 18rem; border-color:red;background-color:#ffd1d1">
          <div class="card-body">
            <h5 class="card-title"><%= playlist.title %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"style="color:red;background-color:#ffd1d1"><%= playlist.category %></li>
            <li class="list-group-item"style="background-color:#ffd1d1"><a href=<%= playlist.link %> class="card-link">Lien</a></li>
            <li class="list-group-item"style="background-color:#ffd1d1"><%= link_to 'Supprimer', playlist, method: :delete, data: { confirm: 'Êtes-vous sûr(e)?' } %></li>
          </ul>
        </div>
      </div>
    <% end %>
    </div>
  </tbody>

<br>

app/views/playlists/new.html.erb
<div style="margin-top:2em;padding:2em;background-color: rgba(250, 237, 237, 0.9);border-radius:30px 30px 30px 30px;height:auto;">
<h1>Nouvelle Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>
</div>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @playlist.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @playlist.link %>
</p>

<p>
  <strong>Category:</strong>
  <%= @playlist.category %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>